# Generated by Django 3.0.9 on 2020-11-30 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='اسم المحل')),
                ('num', models.CharField(default='', max_length=1000, verbose_name='رقم جهاز مدى 1')),
                ('num2', models.CharField(default='', max_length=1000, verbose_name='رقم جهاز مدى 2')),
                ('mobile', models.CharField(max_length=1000, verbose_name='رقم الهاتف')),
                ('author', models.CharField(max_length=1000, verbose_name='المسؤول عن القبض  ')),
            ],
            options={
                'verbose_name': 'محل',
                'verbose_name_plural': 'المحلات',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.DateTimeField(default=django.utils.timezone.now, verbose_name='من')),
                ('to', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الي')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='app.Shop', verbose_name='المحل')),
            ],
            options={
                'verbose_name': 'كشف',
                'verbose_name_plural': 'الكشوفات',
                'ordering': ('-to',),
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(error_messages={'unique': 'عزيزي الموظف رقم العمليه مكرر يرجى مراجعة البحث وشكرا.'}, max_length=10000, unique=True, verbose_name='رقم العمليه')),
                ('deserved_amount', models.FloatField(default=0, verbose_name='المبلغ المستحق')),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='المبلغ المدفوع')),
                ('residual', models.FloatField(blank=True, default=0, null=True, verbose_name='المبلغ المتبقي')),
                ('discount', models.FloatField(blank=True, default=0, null=True, verbose_name='الخصم')),
                ('numa', models.CharField(blank=True, default='-', max_length=10000, null=True, verbose_name='رقم فاتورة المبيعات')),
                ('nume', models.CharField(blank=True, default='-', max_length=10000, null=True, verbose_name='مبلغ فاتورة المبيعات')),
                ('bond_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ القبض')),
                ('peration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ العمليه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='باقي مدفوعات')),
                ('isactive', models.BooleanField(default=False, verbose_name=' تم الدفع')),
                ('rr', models.BooleanField(default=False, editable=False)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي قام باالادخال')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.Shop', verbose_name='المحل')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد للدفع ')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'السندات',
                'ordering': ('-bond_date',),
            },
        ),
    ]
