# Generated by Django 3.0.9 on 2020-12-01 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='peration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ العمليه'),
        ),
        migrations.AlterField(
            model_name='cc',
            name='from1',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='cc',
            name='to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='الي'),
        ),
    ]
