# Generated by Django 3.0.9 on 2020-12-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bond_شخص'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='شخص',
        ),
    ]
